### ISSUE TITLE
Why do you use the same model for both evaluation.py and evaluation-2.py, and why is the model in Greek instead of English?

### ISSUE THREAD

**Issue by 3226462340** [jawaher-is/Emotion_recognition_Wav2Vec2#1]

**Comment by jawaher-is** [comment]
This repo is outdated and incomplete. An updated version of this project is available in [this repo](https://github.com/jawaher-is/XLSER-ar).

For more information, you can look at the [original code](https://colab.research.google.com/github/m3hrdadfi/soxan/blob/main/notebooks/Emotion_recognition_in_Greek_speech_using_Wav2Vec2.ipynb) by https://github.com/m3hrdadfi/soxan
