### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './features/speech_list_train.npy'

### ISSUE THREAD

**Issue by 3226462340** [jawaher-is/Emotion_recognition_Wav2Vec2#2]

**Comment by jawaher-is** [comment]
This repo is outdated and incomplete. An updated version of this project is available in [this repo](https://github.com/jawaher-is/XLSER-ar).

For more information, you can look at the [original code](https://colab.research.google.com/github/m3hrdadfi/soxan/blob/main/notebooks/Emotion_recognition_in_Greek_speech_using_Wav2Vec2.ipynb) by https://github.com/m3hrdadfi/soxan
